### ISSUE TITLE
Cant access monocular throug nginx / ingress

### ISSUE THREAD

**Issue by J4ke117** [helm/charts#2523] opened 2017-10-19 09:01 UTC
**Is this a request for help?**:
yes
----
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm:  v2.6.2
Kubernetes: v1.7.8
Kubeadm: 1.8
Ubuntu: 16.04

**Which chart**:
[https://kubeapps.com/charts/stable/nginx-ingress](url)

**What happened**:
The External-IP from the Nginx ingress Controller service stays in pending. I want to use monocular on my bare-metal setup with kubeadm. When i use `kubectl get ingress`  it should deliver me the IP Address where i can access the monocular UI, but it leads me to the Apache2 Ubuntu default page. I can open the monocular ui when i use the IP Address from the monocular ui service, but the charts section is loading forever and in the deployment section it says me i have no deployments running. At this point I'm not sure if it is a issue with monocular  or nginx.  I don't have a lot of experience with docker/kubernetes and I'm trying to get slowly into the whole container topic. 
If someone could help me or has some ideas I would really appreciate it.

`kubectl get services --all-namespaces`
```
existing-badger-monocular-api                     NodePort       10.101.27.231    <none>        80:32089/TCP                 45m
existing-badger-monocular-prerender               NodePort       10.96.244.2      <none>        80:32157/TCP                 45m
existing-badger-monocular-ui                      NodePort       10.106.146.202   <none>        80:32167/TCP                 45m
existing-badger-redis                             ClusterIP      10.97.80.198     <none>        6379/TCP                     45m
kubernetes                                        ClusterIP      10.96.0.1        <none>        443/TCP                      1h
quarreling-sponge-nginx-ingress-controller        LoadBalancer   10.109.218.104   <pending>     80:31278/TCP,443:30129/TCP   15m
quarreling-sponge-nginx-ingress-default-backend   ClusterIP      10.102.199.158   <none>        80/TCP                       15m
```
`kubectl get pods --all-namespaces`
```
default       existing-badger-monocular-api-1387714561-n0xc9                    1/1       Running   0          42m
default       existing-badger-monocular-api-1387714561-r3hll                    1/1       Running   1          42m
default       existing-badger-monocular-prerender-1015882994-3fvv3              1/1       Running   0          42m
default       existing-badger-monocular-ui-1457801264-0hvc3                     1/1       Running   0          42m
default       existing-badger-monocular-ui-1457801264-mzszn                     1/1       Running   0          42m
default       existing-badger-redis-2266821072-382ql                            1/1       Running   0          42m
default       maudlin-octopus-chaoskube-1054433587-f465l                        1/1       Running   0          27s
default       quarreling-sponge-nginx-ingress-controller-3955310568-d8tw4       1/1       Running   0          13m
default       quarreling-sponge-nginx-ingress-default-backend-263082663-cjr2j   1/1       Running   0          13m
kube-system   etcd-jake-desktop                                                 1/1       Running   0          56m
kube-system   kube-apiserver-jake-desktop                                       1/1       Running   0          56m
kube-system   kube-controller-manager-jake-desktop                              1/1       Running   0          56m
kube-system   kube-dns-3036648637-38zj8                                         3/3       Running   0          57m
kube-system   kube-proxy-p3dtw                                                  1/1       Running   0          57m
kube-system   kube-scheduler-jake-desktop                                       1/1       Running   0          56m
kube-system   tiller-deploy-1936853538-jw21k                                    1/1       Running   0          51m
kube-system   weave-net-4b2mm                                                   2/2       Running   0          55m
```
`helm list`
```
existing-badger         1               Thu Oct 19 09:04:47 2017        DEPLOYED        monocular-0.4.9         default
maudlin-octopus         1               Thu Oct 19 09:46:53 2017        DEPLOYED        chaoskube-0.5.0         default
quarreling-sponge       1               Thu Oct 19 09:34:18 2017        DEPLOYED        nginx-ingress-0.8.4     default
```

**What you expected to happen**:
Services are working and i can use monocular.

**How to reproduce it** (as minimally and precisely as possible):
Used this guide to set up a kubernetes cluster:
 [https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/](url)

Steps I did for setting up my cluster:
`sudo swapoff -a`
`sudo sysctl net.bridge.bridge-nf-call-iptables=1`
`sudo kubeadm init --kubernetes-version stable-1.7`
`mkdir -p $HOME/.kube `
`sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config`
`sudo chown $(id -u):$(id -g) $HOME/.kube/config`
`export kubever=$(kubectl version | base64 | tr -d '\n')`
`kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$kubever"`
`kubectl create clusterrolebinding permissive-binding \
  --clusterrole=cluster-admin \
  --user=admin \
  --user=kubelet \
  --group=system:serviceaccounts`
`kubectl taint nodes --all node-role.kubernetes.io/master-`
`helm init`
`helm install stable/nginx-ingress --set controller.hostNetwork=true`
`helm install monocular/monocular --set redis.persistence.enabled=false`

**Anything else we need to know**:
I'm behind a company proxy and use cntlm. I have set the proxy settings in /etc/environments and for apt-get in /etc/apt/apt.conf.
Also i tried these steps from [https://github.com/weaveworks/weave/issues/3016](url) but its still not working.

**Comment by mattfarina** [comment] 2017-10-19 14:30
cc: @prydonius @jackzampolin @mgoodness @chancez 

cc'ing the maintainer for monocular and nginx-ingress

**Comment by prydonius** [comment] 2017-10-19 15:28
@J4ke117 Your bare-metal setup won't support automatically provisioning the IP address, which is why you get a forever pending state for the Nginx Ingress IP. You should instead be able to access it by NodePort ($NODEIP:31278), and you can setup a manual load balancer to point to that port on all your nodes if your infrastructure allows it. Does accessing it via NodePort work?

**Comment by prydonius** [comment] 2017-10-19 16:34
@J4ke117 actually since you're using hostNetwork, you should be able to access the ingress controller on port 80 on the node ($NODEIP:80)

**Comment by J4ke117** [comment] 2017-10-20 10:35
@prydonius thank you for the fast respond. I used `kubectl get ingress` and it gave me my master node IP back, with the port 80. When I type it in my browser on my master node http://MASTERNODEIP:80 it shows me this page [https://assets.digitalocean.com/articles/lamp_1404/default_apache.png](url). If I access the interface through the Monocular-Ui nodeport IP, it works but some sections are not working as I mentioned above. As far as I unterstood there is something wrong with routing inside my master and Nginx / Ingress will not work, because it is a load balancer which is not supported by my setup. Am I right?

**Comment by J4ke117** [comment] 2017-11-09 08:44
I got Monocular running with Rook and this guide [https://github.com/luxas/kubeadm-workshop/tree/master](url) which is close to my setup. 
I deployed nginx ingress with: 
`helm install stable/nginx-ingress --set controller.hostNetwork=true` 
and monocular with:
`helm repo add monocular https://kubernetes-helm.github.io/monocular`
`helm install monocular/monocular`
Now it is possible to access monocular from outside the cluster. Only the chart section isn't working, it doesn't show me any charts to install.

**Comment by prydonius** [comment] 2017-11-10 13:45
Hi @J4ke117, I get the feeling that Apache is running on your Nodes and taking up port 80, meaning that your nginx ingress controller is not able to bind to port 80 on the node. Do you get that Apache page when the ingress controller is uninstalled? Maybe you should SSH into your nodes and disable any services running on port 80.

**Comment by J4ke117** [comment] 2017-11-10 14:14
Hey @prydonius `netstat -tulpn | grep :80`

```
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      13628/nginx.conf
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      13628/nginx.conf
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      13628/nginx.conf
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      13628/nginx.conf
tcp6       0      0 :::80                   :::*                    LISTEN      13628/nginx.conf
tcp6       0      0 :::80                   :::*                    LISTEN      13628/nginx.conf
tcp6       0      0 :::80                   :::*                    LISTEN      13628/nginx.conf
tcp6       0      0 :::80                   :::*                    LISTEN      13628/nginx.conf
```
Thanks for your help, but this shouldn't be the problem. I remember having this problem with apache but then nginx ingress doesn't start at all, so i deactivated it. I tried to reproduce it at home with a different machine also running Ubuntu and got the same situation.

**Comment by prydonius** [comment] 2017-11-10 14:19
What are the response headers from `curl -vv $NODEIP:80`? Does the `Server` header indicate whether it's nginx or Apache?

**Comment by J4ke117** [comment] 2017-11-10 15:06
```
> User-Agent: curl/7.47.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.13.4
< Date: Fri, 10 Nov 2017 14:58:18 GMT
< Content-Type: text/html
< Content-Length: 185
< Connection: keep-alive
< Strict-Transport-Security: max-age=15724800; includeSubDomains;
< Proxy-Connection: keep-alive
```
I use a Wlan Interface to connect my cluster to a laptop for internet access and my ethernet for the connection to a pi as a worker node, maybe this is a problem using two interfaces? At the moment every pod is running on my master.

**Comment by prydonius** [comment] 2017-11-13 10:28
Looks like you're getting to nginx, where do you get redirected to if you add `-L` to your curl command?

**Comment by J4ke117** [comment] 2017-11-13 11:39
`curl -vv 192.168.0.2:80 -L`

```
* Rebuilt URL to: 192.168.0.2:80/
*   Trying 192.168.1.1...
* Connected to 192.168.1.1 (192.168.1.1) port 3128 (#0)
> GET http://192.168.0.2:80/ HTTP/1.1
> Host: 192.168.0.2
> User-Agent: curl/7.47.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.13.4
< Date: Mon, 13 Nov 2017 11:18:39 GMT
< Content-Type: text/html
< Content-Length: 185
< Connection: keep-alive
< Location: https://192.168.0.2/
< Strict-Transport-Security: max-age=15724800; includeSubDomains;
< Proxy-Connection: keep-alive
<
* Ignoring the response-body
* Connection #0 to host 192.168.1.1 left intact
* Issue another request to this URL: 'https://192.168.0.2/'
* Found bundle for host 192.168.0.2: 0x5593975f7400 [can pipeline]
* Hostname 192.168.1.1 was found in DNS cache
*   Trying 192.168.1.1...
* Connected to 192.168.1.1 (192.168.1.1) port 3128 (#1)
* Establish HTTP proxy tunnel to 192.168.0.2:443
> CONNECT 192.168.0.2:443 HTTP/1.1
> Host: 192.168.0.2:443
> User-Agent: curl/7.47.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied OK to CONNECT request
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 597 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
* Closing connection 1
```

**Comment by prydonius** [comment] 2017-11-13 12:22
Hmm, I'm not sure exactly what the issue is here. Could it be related to the SSL issue?

**Comment by J4ke117** [comment] 2017-11-13 13:47
Thanks for trying to help me I'm really interested in getting Monocular running in my setup. Sry I don't know which SSL issue you mean.

**Comment by prydonius** [comment] 2017-11-13 13:56
the `curl` request shows that it's closing the connection because the server certificate verification failed:

```
* server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
* Closing connection 1
```

**Comment by J4ke117** [comment] 2017-11-13 13:59
Ok I will try to solve it and test it again.

**Comment by J4ke117** [comment] 2017-11-15 10:10
I built Monocular with docker compose up, then the Chart Section is working. Deployments and installing charts from the UI isn't working but I suppose this is because, I haven't launchend Monocular through helm install?

**Closed as completed** 2018-04-14 11:49 UTC
Labels: lifecycle/rotten
