### ISSUE TITLE
[stable/grafana] Adding a datasource did not work

### ISSUE THREAD

**Issue by r-divakaran-hrs** [helm/charts#8928] opened 2018-10-31 12:55 UTC
**Is this a request for help?**:
Yes its a help request.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

I am using the prometheus operator helm chart and everything is working, expect adding a new data source. 
I have enabled the extra data sources option and the side card container is running. 

The datasource I am trying to add is of type cloudwatch. The configmap used looks as below
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-grafana-datasource
  labels:
     grafana_datasource: "1"
  namespace: monitoring
data:
  datasource.yaml: |-
    # config file version
    apiVersion: 1

    datasources:
      - name: Cloudwatch
        type: cloudwatch
        jsonData:
          authType: keys
          defaultRegion: eu-west-1
        secureJsonData:
          accessKey: "AAAAAAAAAAAAAA"
          secretKey: "BBBBBBBBBBBBBBBBBBBBBBBB"
```
When I apply the configmap its getting created successfully and could see as below in grafana-sc-datasources container's logs
```
Working on configmap cloudwatch-grafana-datasource
Configmap with label found
File in configmap datasource.yaml ADDED
```
Checked the grafana container logs and didn't see any errors.
As per https://github.com/helm/charts/tree/master/stable/grafana#sidecar-for-datasources I noticed it is mentioned the configmap will be created and picked up during start up. So I tried restarting grafana pod, but with no luck.
To check if my access credentials are correct, using same data when I try to create it from Grafana UI, its working properly.

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
````

**Which chart**:
Using prometheus-operator chart.

**What happened**:
Adding extra data source using configmaps is not working as expected. Please check my explaination above.

**What you expected to happen**:
Expected to see the datasource ready to be consumed as the configmap is created without errors and also container logs looks clean.

**How to reproduce it** (as minimally and precisely as possible):
Please try creating a data source using the configmap I posted above. You might need to use valid AWS access key and password.

**Anything else we need to know**:

**Comment by r-divakaran** [comment] 2018-11-01 12:35
Also noticed that with side car data sources enabled and when the chart is installed with additional data source yamls as part of chart, its deploying only the additional one.

**Comment by paskal** [comment] 2018-11-02 08:08
Reproduced. It seems related to grafana sidecar itself: it loads only last one datasource it found:
```
➜  Desktop  kubectl logs pods/prometheus-grafana-6d54c8f5b9-szfh2 -c grafana-sc-datasources | grep 'Configmap with label found' -C1
Working on configmap prometheus-operator-grafana-datasource
Configmap with label found
File in configmap datasource.yaml ADDED
--
Working on configmap cloudwatch-grafana-datasource
Configmap with label found
File in configmap datasource.yaml ADDED
--
Working on configmap prometheus-4
Configmap with label found
File in configmap datasource.yaml ADDED
--
Working on configmap prometheus-2
Configmap with label found
File in configmap datasource.yaml ADDED
➜  Desktop  kubectl exec -it prometheus-grafana-6d54c8f5b9-szfh2 -c grafana-sc-datasources -- cat /etc/grafana/provisioning/datasources/datasource.yaml
apiVersion: 1
datasources:
- name: Prometheus-2
  type: prometheus
  url: http://prometheus-prometheus:9091
  access: proxy
```
Please, rename the issue to [stable/grafana] - it's caused by that chart, not to prometheus-operator. Ping @rimusz @davidkarlsen

**Comment by paskal** [comment] 2018-11-02 08:36
Okay, I'm terribly sorry, that's all false positive, noone from pinged people actually have to do anything with this.
The key to this issue is pretty simple: if you provide the same name of datasources file in multiply configmaps, only the last one will be used, in this case you are rewriting `datasource.yaml`:
```data:
  datasource.yaml: |-```
To add new datasource, please use any other name, and it will be added alongside with old one. The way to improve prometheus-operator chart from this issue I can think about is templatize the name so even if someone copies it, he or she will think about renaming this file, or it will be unique by the template used.
@r-divakaran, please rename the issue back to [stable/prometheus-operator], and feel free to close it:)

**Comment by r-divakaran** [comment] 2018-11-02 08:50
Thanks again @paskal

**Closed as completed by r-divakaran** 2018-11-02 08:50 UTC
