### ISSUE TITLE
[stable/redis] prometheus metrics exporter is crashlooping (missing `/bin/sh`) version 5.3.0

### ISSUE THREAD

**Issue by niels-s** [helm/charts#10733] opened 2019-01-17 14:54 UTC
**Version of Helm and Kubernetes**: 

Helm
```
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
```

Kubernetes
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.9-gke.7", GitCommit:"572a070abf31a08a8f0d104220da467ea1e3d5f2", GitTreeState:"clean", BuildDate:"2018-11-14T05:26:58Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: stable/redis

**What happened**: The prometheus metrics exporter pod can't start properly. It's stuck in a crashloop because it's missing `/bin/sh`. We get the following error message:
```
Error: failed to start container "metrics": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"
```

**What you expected to happen**: The pod should start properly.

**How to reproduce it** (as minimally and precisely as possible):
```yaml
- stable/redis:
    version: ~> 5.3.0
    values:
      metrics:
        enabled: true
      usePassword: false
      cluster:
        enabled: false
        slaveCount: 0
```

**Anything else we need to know**:

This bug is introduced in PR https://github.com/helm/charts/pull/10216, the start command for the metrics pod is adjusted but the imaged used `oliver006/redis_exporter` is based on the scratch image so there is no `/bin/sh` available see https://github.com/oliver006/redis_exporter/commit/8c89e535f9aedcd0ca5a170405e287fca643721d

**Comment by juan131** [comment] 2019-01-18 10:24
Hi @niels-s 

I'm able to reproduce the issue. Thanks so much for reporting it!! Working a PR to fix it

**Comment by okgolove** [comment] 2019-01-21 12:02
Hello! Have same thing.
It seems it's because of using `scratch` - https://github.com/oliver006/redis_exporter/blob/master/Dockerfile#L38

**Comment by juan131** [comment] 2019-01-24 07:59
@javsalgar is working on a fix for this issue. We'll update this thread as soon as it's been released a new chart with the fix.

**Closed as completed** 2019-01-31 12:12 UTC
