### ISSUE TITLE
[stable/sonarqube] Upgrade Postgresql/Mysql sub chart version

### ISSUE THREAD

**Issue by sparqueur** [helm/charts#20414] opened 2020-01-29 08:23 UTC
Postgresql and Mysql charts are very old (> 2 years)
postgresql : 0.8.3 
mysql : 0.6.0

We are missing extra feautre that are available in more recent version.

**Is your feature request related to a problem? Please describe.**
I need to add anotations to Postgresql PVC. This is not possible in current chart version.

**Describe the solution you'd like**
Upgrade chart version to latest versions

**Comment by oscarlofwenhamn** [comment] 2020-01-29 12:54
Duplicate of #20386

**Closed as completed** 2020-01-30 17:10 UTC
