### ISSUE TITLE
helm charts incubator - new location - broken index? 

### ISSUE THREAD

**Issue by smirnov-mi** [helm/charts#24438] opened 2020-12-03 18:42 UTC
Hi guys

trying to update / install a chart from new location I got:

` message": "Error fetching helm URLs: [Error in HTTP GET of [https://charts.helm.sh/incubator/patroni-0.16.3.tgz], received: 404 Not Found]",`

**Comment by urmet** [comment] 2020-12-03 19:28
Looks like the same issue as in #24426 but for incubator instead of stable

**Comment by scottrigby** [comment] 2020-12-07 16:00
This is a duplicate of #24426 and was fixed in https://github.com/helm/charts/pull/24430. If you're still getting this error, try `helm repo update` or delete and re-add the repo.

**Comment by urmet** [comment] 2020-12-07 16:07
but it's not fixed. I checked the index _just now_
```
$ curl -s https://charts.helm.sh/incubator/index.yaml | grep patroni-0.16.3
    - https://charts.helm.sh/incubator/patroni-0.16.3.tgz
```

**Comment by scottrigby** [comment] 2020-12-07 16:25
My mistake, you are correct. Let's fix this

**Comment by scottrigby** [comment] 2020-12-07 16:47
@urmet please try again

**Comment by urmet** [comment] 2020-12-07 17:08
incubator looks all fine now. But I did find 2 bad paths in stable index when I started looking. 
```
$ curl -s https://charts.helm.sh/stable/index.yaml | grep tgz | grep -v "/packages/"
    - https://charts.helm.sh/stable/percona-1.2.2.tgz
    - https://charts.helm.sh/stable/percona-xtradb-cluster-1.0.7.tgz
```
not actually relevant to this issue and these two are not the newest versions of their charts, so really unlikely to be noticed by users.

**Comment by scottrigby** [comment] 2020-12-07 17:38
Thanks @urmet, closing this issue. Linked a PR to fix those, and thanked you there.

**Closed as completed by scottrigby** 2020-12-07 17:38 UTC

**Comment by smirnov-mi** [comment] 2020-12-08 08:12
thank you guys! remove and readd repo helped then.
