### ISSUE TITLE
Traefik install error: Duplicate value

### ISSUE THREAD

**Issue by neumachen** [helm/charts#2644] opened 2017-11-02 01:17 UTC
**Is this a request for help?**:
Help

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
```
Kubernetes 1.8.1-gke.0
```
```
$ helm version
Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
```

--

**Which chart**: 
traefik

**What happened**:
```
Error: release traefik failed: Service "traefik-traefik" is invalid: spec.ports[1].targetPort: Duplicate value: intstr.IntOrString{Type:0, IntVal:80, StrVal:""}
```

**What you expected to happen**:
No errors

**How to reproduce it** (as minimally and precisely as possible):
Install latest Traefik chart

**Anything else we need to know**:
None

**Comment by raykrueger** [comment] 2017-11-03 02:31
Seems to have to do with the logic around ssl being enabled or not. This might help as a workaround...

    helm install stable/traefik --set=ssl.enabled=true

I'm looking at the logic to see if I can come up with a fix.

**Comment by krancour** [comment] 2017-11-06 16:19
This is a duplicate of #2472, but I propose we leave this one open in favor of #2472 because this one already has a pull request associated with it.

**Closed as completed** 2017-11-07 17:55 UTC
