### ISSUE TITLE
[stable/jenkins] Chart version 0.6.3 has plugin dependency errors out-of-the box

### ISSUE THREAD

**Issue by twpayne** [helm/charts#1134] opened 2017-05-22 15:40 UTC
Installing Jenkins with the latest chart results in Jenkins reporting a number of plugin errors:

```
There are dependency errors loading some plugins:
Pipeline: Declarative Extension Points API v1.1.4
Pipeline: Job v2.12 failed to load. Fix this plugin first.
Pipeline Graph Analysis Plugin v1.3
Pipeline: Job v2.12 failed to load. Fix this plugin first.
Pipeline: REST API Plugin v2.6
Pipeline Graph Analysis Plugin v1.3 failed to load. Fix this plugin first.
Pipeline v2.5
Pipeline: Job v2.12 failed to load. Fix this plugin first.
Pipeline: Stage View Plugin v2.6
Pipeline: Job v2.12 failed to load. Fix this plugin first.
Pipeline: Model Definition v1.1.4
Pipeline: Multibranch v2.14 failed to load. Fix this plugin first.
Pipeline: Declarative Agent API v1.1.1
Pipeline: Declarative Extension Points API v1.1.4 failed to load. Fix this plugin first.
Pipeline: Job v2.12
You must update Jenkins from v2.46.2 to v2.60 or later to run this plugin.
Pipeline: Multibranch v2.14
Pipeline: Job v2.12 failed to load. Fix this plugin first.
```

This occurs reproducibly on a kops-created cluster with Jenkins installed with the command:
```
$ helm install stable/jenkins
```

Once the Jenkins master is up-and-running, login to Jenkins as `admin`. The dependency errors are visible in the web interface:

![stable-jenkins-dependency-errors](https://cloud.githubusercontent.com/assets/6942/26316382/62a61e60-3f14-11e7-8d0d-091ed3d63ab1.png)

Using the [latest Jenkins image](https://hub.docker.com/r/jenkinsci/jenkins/tags/) (pushed on Sunday 21 May) seems to resolve the problem:

```
helm install --set Master.ImageTag=latest stable/jenkins
```

**Comment by lachie83** [comment] 2017-05-23 05:02
I'm unable to reproduce this issue running this command `helm install --set Master.ImageTag=latest stable/jenkins` Cluster comes up with all plugins installed. Are you installing to a fresh PV?

**Comment by twpayne** [comment] 2017-05-23 08:19
@lachie83, that's correct, the problem does not occur with `--set Master.ImageTag=latest`. It only occurs with the default `Master.ImageTag` ([2.46.2](https://github.com/kubernetes/charts/blob/master/stable/jenkins/values.yaml#L9)).

**Comment by lachie83** [comment] 2017-05-23 17:22
I believe this is related to the following -- https://github.com/jenkinsci/docker/pull/495

**Comment by lachie83** [comment] 2017-05-23 17:23
And this issue -- https://github.com/jenkinsci/docker/issues/494

**Comment by twpayne** [comment] 2017-05-23 22:59
Thanks @lachie83! The upstream issue does look like the culprit. Thank you for your investigation. Feel free to close this issue with a "waiting-for-upstream-fix" or similar :)

**Comment by lachie83** [comment] 2017-05-28 07:46
Also this -- https://github.com/kubernetes/charts/pull/1178

**Comment by lachie83** [comment] 2017-06-02 20:09
@unguiculus can you let us know which release of Jenkins will have your patch as I see it's merged.

**Comment by lachie83** [comment] 2017-06-05 18:05
Closing based on merge of https://github.com/kubernetes/charts/pull/1178

**Closed as completed by lachie83** 2017-06-05 18:05 UTC
