### ISSUE TITLE
RabbitMQ high CPU usage on idle VM

### ISSUE THREAD

**Issue by TomaszUrugOlszewski** [helm/charts#3855] opened 2018-02-23 17:34 UTC
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm: 2.8.0
Kubectl server: 1.7.12-gke.1 (current) (It's GCP)

**Which chart**:
stable/rabbitmq

**What happened**:
High CPU usage on idle VM with only RabbitMQ running, generated by readiness/liveness probes. Basing on Stackdriver charts I see 100% CPU usage on n1-standard-2 VM. After forking chart, replacing probes with simple tcpSocket to 15672 port, it decreased to ~0%.

![image](https://image.ibb.co/kjLUqx/Node_CPU_utilization.png)

**What you expected to happen**:
To allow customizing health checks, use tcpSocket or httpGet instead of exec probes.

**How to reproduce it** (as minimally and precisely as possible):
Run it on GCP with n1-standard-2 VM type, and watch

**Comment by sbnl** [comment] 2018-03-15 09:48
Would like to add that I'm also seeing this on GCP K8s 1.8.7-gke.1aprox 60% usage at idle.
n1-standard-1 (3.7G) free tier.
erl_child_setup and beam.smp being the consumers a around 25% each.

edit : chart : rabbitmq-0.6.17

edit: Upgraded to 0.6.25, no change.

**Comment by macropin** [comment] 2018-04-05 03:43
We're seeing this as well  (k8s 1.8.11, rabbitmq-0.6.25). I believe this is caused by a longstanding erlang issue related to nofile ulimit which has been known since at least 2014...

See https://github.com/bitnami/bitnami-docker-rabbitmq/pull/63

**Comment by robermorales** [comment] 2018-04-23 17:41
cool! the solution of disabling readiness and liveness worked so far! but is there any option to change the ulimit in the docker image, the chart, or the deployment itself?

**Comment by thomas-riccardi** [comment] 2018-04-23 17:53
@robermorales the docker image including the fix (https://github.com/bitnami/bitnami-docker-rabbitmq/pull/69) is being prepared by bitnami; then the default value should be OK, but we should still expose it in the chart values.

**Comment by robermorales** [comment] 2018-04-23 19:12
thanks!

**Comment by thomas-riccardi** [comment] 2018-05-02 09:11
The fix has been released in docker images `3.7.4-r4` and `3.6.15-r4` (and their aliases: `3.7.4`, `3.7`, `3.6.15` and `3.6`).

Since #4591 the `values.yaml` became non-prod, and the default image tag is the floating tag `3.7.4` instead of `3.7.4-r1`. (`values-production.yaml` still refers to `3.7.4-r1`).
Alas, we also have by default `pullPolicy: IfNotPresent` so in practice the floating tag is not a great idea...

I'm not sure if `values-production.yaml` is a good pattern; maybe it could just overrides some values instead of redefining everything. (only uses: redis and rabbitmq).

Maybe we should remove the floating tag and use read-only tags: `3.7.4-r4`.


In any case, we should bump to `-r4` to get the high CPU usage fix.

**Comment by rips-hb** [comment] 2018-06-20 14:11
I still have the exact same issue in `3.7.6-r8`.

**Comment by thomas-riccardi** [comment] 2018-06-20 14:18
@rips-hb I also have some high CPU usage, but it's periodic, not constant. I found out it's the probes (`rabbitmqctl status`) which use that much CPU periodically; it's a different issue (that should be created here), and I'm not sure what to do to fix it.

**Comment by rips-hb** [comment] 2018-06-20 15:04
@thomas-riccardi for me it is constant unfortunately and I could resolve it by disabling liveness and readiness as suggested in this thread. Since it is only a test system that is no problem but I would rather have this checks on a production system. I will investigate a bit more and if I find something else I will create a new ticket.

**Comment by nerumo** [comment] 2018-08-19 07:07
still an issue

**Comment by macropin** [comment] 2018-09-25 02:56
The fix https://github.com/bitnami/bitnami-docker-rabbitmq/pull/63 is incomplete and does not set the ulimit for the liveness / readiness probes.

**Comment by thomas-riccardi** [comment] 2018-09-25 08:59
@macropin you are right. 
However, I did not find a difference in execution time for `rabbitmqctl status` (or `rabbitmqctl node_health_check`) with and without `ulimit -n 1024` (or `ulimit -n 65536`), so trying to add the `ulimit -n` to healtchecks will probably *not* help.

**Comment by thomas-riccardi** [comment] 2018-09-25 09:02
@macropin see also `rabbitmq-ha` advancements: #7378 (and #7752).

**Comment by intelfx** [comment] 2018-10-02 15:12
Also I concur with @thomas-riccardi's findings — I did some testing too, and it turns out that even setting ridiculously low `ulimit -n 128` does not help neither to reduce the probes' CPU time nor to reduce overall Pod's CPU usage.

**Comment by alexsandro-xpt** [comment] 2018-10-06 14:01
could it fixed at `helm install`? I have same problem here.

**Comment by thomas-riccardi** [comment] 2018-11-06 10:11
@TomaszUrugOlszewski It should be fixed by #8140 (and subsequent fixes), modulo the issue about disk or memory alarms (see #8635).

**Comment by FrankXuLei** [comment] 2018-11-09 16:35
rabbitmq 3.7.8 ，Erlang 21.1 same issue,high cpu useage. qps about 200/s

**Comment by alexsandro-xpt** [comment] 2018-11-13 19:40
But, Is this was fixed?

**Comment by dNetGuru** [comment] 2018-11-19 09:08
I'm seeing the exact same behavior on 3.7.8 (Erlang 21.1) with very high CPU usage when idle and as a workaround disabling both the readiness and liveliness checks seems to fix the issue.

**Comment by javsalgar** [comment] 2018-12-07 14:34
Hi,

Thanks for the feedback. If this issue is constant, then maybe it makes sense to change the readiness/liveness probes to simple tcp port checking. Thoughts on that?

**Comment by dNetGuru** [comment] 2018-12-08 02:37
@javsalgar I tried again with the latest version of the chart (rabbitmq-4.0.1) with Rabbitmq 3.7.9 (Erlang 21.1) and this problem does not seem to happen anymore.

**Comment by juan131** [comment] 2019-01-02 12:20
Hi everyone, 

Do you still suffer High CPU usage because of readiness/liveness probes in the latest versions of the cart?? 

I agree with @javsalgar, we can make simpler probes (such as tcp port checking) or decrease the frequency if you're running into issues because of that.

**Comment by desaintmartin** [comment] 2019-01-03 08:54
In my case, I greatly reduced the frequency of the probes.

**Comment by juan131** [comment] 2019-01-03 09:37
What values did you use @desaintmartin ?

**Comment by desaintmartin** [comment] 2019-01-03 09:38
```yaml
  livenessProbe:
    timeoutSeconds: 30
    periodSeconds: 30
  readinessProbe:
    timeoutSeconds: 30
    periodSeconds: 30
```

**Closed as completed** 2019-01-03 15:34 UTC

**Comment by macropin** [comment] 2019-01-04 02:16
So the "fix" isn't a fix, rather a workaround. This should be reopened.

**Comment by juan131** [comment] 2019-01-04 12:38
Hi @macropin 

Currently liveness/readiness probes use `curl` instead of `rabbitmqctl`. Why do you consider necessary to update the `ulimits` on the probes?

**Comment by macropin** [comment] 2019-01-05 05:48
Oh that's great. I missed that change. The High cpu usage of `rabbitmqctl` was due to it not inheriting the entrypoint `ulimit` which cased a cpu usage issue with the Erlang JVM.

**Comment by juan131** [comment] 2019-01-08 14:56
Yes, it was one of the reasons why the CPU was so high. That's why they were moved to curl on
https://github.com/helm/charts/pull/8140

**Comment by Artimi** [comment] 2019-04-01 10:43
Hi, I've found another reason why RabbitMQ can have noticeable CPU usage when in idle or under a light load. RabbitMQ is running on Erlang and it is using its scheduling capabilities. To schedule a process Erlang is using scheduler threads and its number by default depends on a number of logical cores. And this is a problem when running in docker/kubernetes because RabbitMQ will think it has more resources than it actually has. In our case, a RabbitMQ node is running on a server with 40 cores but we are limiting it only to have 1 core in Kubernetes. Erlang will run 40 scheduler threads that are constantly context switching which generates the cpu usage. When I set the number of scheduler threads to 1 the CPU usage dropped from 23 % to 3 %. 
You can check how many scheduler threads you are using with `rabbitmqctl status`:
```
$ rabbitmqctl status
...
{erlang_version,
     "Erlang/OTP 20 [erts-9.3.3.3] [source] [64-bit] [smp:40:40] [ds:40:40:10] [async-threads:640] [hipe] [kernel-poll:true]\n"},
...
```
numbers after `smp` are the number of threads. For more info see [Erlang scheduler details](https://hamidreza-s.github.io/erlang/scheduling/real-time/preemptive/migration/2016/02/09/erlang-scheduler-details.html). You can set the value using environment variable:
```
RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="+S 1:1"
```

**Comment by infa-ddeore** [comment] 2019-04-10 16:05
@Artimi how did you set"RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS" with rabbitmq helm?

**Comment by Artimi** [comment] 2019-04-11 06:37
@infa-ddeore We actually are not using helm, just custom made kubernetes deployment. I just wrote it here because I had similar problems as are in this issue.

**Comment by infa-ddeore** [comment] 2019-04-12 00:32
@thomas-riccardi thanks for the pointers, for now I will update stable/rabbitmq chart locally with this variable and deploy that

**Comment by infa-ddeore** [comment] 2019-04-12 01:16
@Artimi setting "RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS" to "+S 1:1" doesn't seem helping me, I will try disabling liveness and readyness checks, my rmq is 3.7.8 and erlang 21

**Comment by juan131** [comment] 2019-04-15 08:04
Thanks for reporting it @Artimi 

I just created a PR so the user has a couple of parameters to limit the number of scheduler threads.

**Comment by sc-chad** [comment] 2020-04-01 04:32
This was still an issue on 3.8.3 with Kubernetes.  Adding the environment variable via rabbitmq-env.conf reduced our cpu usage by 300-400%.

**Comment by zzguang520** [comment] 2021-08-03 07:15
same issues in helm chart rabbitmq-ha-1.47.1
