### ISSUE TITLE
Concourse CI workers failing on kubernetes

### ISSUE THREAD

**Issue by jonasdkhansen** [helm/charts#4902] opened 2018-04-11 10:10 UTC
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm: v2.9.0-rc3
Kubernetes: v1.9.3-gke.0

**Which chart**:
stable/concourse

**What happened**:
worker pods keeps failing, with the error message: 
failed to connect to TSA: dial tcp: address jaunty-magpie-web: missing port in address

**What you expected to happen**:
Workers running and i could run the command fly workers and see the workers.

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/concourse, and when everything is running, the workers starts failing.

**Anything else we need to know**:
I have tried the default values file, and with a nginx ingress controller.

**Comment by brunoban** [comment] 2018-04-11 10:43
Hey Jonas,

This is a duplicate of https://github.com/kubernetes/charts/issues/4812

I'm working on a PR to fix it in the chart, but in the mean time the comment I added to the issue has the instructions to fix it.

**Comment by jonasdkhansen** [comment] 2018-04-11 11:06
@brunoban thank you very much Bruno! The workers are running now, closing the issue.

**Closed as completed** 2018-04-11 11:06 UTC
