### ISSUE TITLE
Adding a datasource did not work

### ISSUE THREAD

**Issue by r-divakaran-hrs** [helm/charts#8927] opened 2018-10-31 12:53 UTC
**Is this a request for help?**:
Yes its a help request.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
````

**Which chart**:
Using prometheus-operator chart.

**What happened**:
Adding extra data source using configmaps is not working as expected. Please check my explaination above.

**What you expected to happen**:
Expected to see the datasource ready to be consumed as the configmap is created without errors and also container logs looks clean.

**How to reproduce it** (as minimally and precisely as possible):
Please try creating a data source using the configmap I posted above. You might need to use valid AWS access key and password.

**Anything else we need to know**:

**Comment by r-divakaran** [comment] 2018-10-31 12:55
Duplicate of another one. Created by mistake.

**Closed as completed by r-divakaran** 2018-10-31 12:55 UTC
