### ISSUE TITLE
Is foldersFromFilesStructure still valid for dashboardProviders? 

### ISSUE THREAD

**Issue by eesperi** [helm/charts#23034] opened 2020-07-01 20:57 UTC
**Describe the bug**
I'm using prometheus-operator. I am disabling sidecar dashboards and provider. I am modifying prometheus-operator Grafana deployment, and removing sc-dashboardprovider.yaml I am using a custom dashboardProvider:

grafana:
  defaultDashboardsEnabled: false
  sidecar:
    dashboards:
      enabled: false
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: test
        type: file
        disableDeletion: true
        editable: false        
        options:
          path: /var/lib/grafana/dashboards/test
          foldersFromFileStructure: true

**Version of Helm and Kubernetes**:
Helm: 3.2.4
Kubernetes: 1.17.3

**Which chart**:
prometheus-operator

**What happened**:
I expected folders to be created in the dashboard that mirror the folders and dashboards that I place in /var/lib/grafana/dashboards/test. Instead, if I where to do something like /var/lib/grafana/dashboards/test/server/test.json, the dashboard in Grafana appears under the General folder. 

**What you expected to happen**:
[https://grafana.com/docs/grafana/latest/administration/provisioning/](https://grafana.com/docs/grafana/latest/administration/provisioning/)

Provision folders structure from filesystem to Grafana
If you already store your dashboards using folders in a git repo or on a filesystem, and also you want to have the same folder names in the Grafana menu, you can use foldersFromFilesStructure option.

For example, to replicate these dashboards structure from the filesystem to Grafana,

/etc/dashboards
├── /server
│   ├── /common_dashboard.json
│   └── /network_dashboard.json
└── /application
    ├── /requests_dashboard.json
    └── /resources_dashboard.json
you need to specify just this short provision configuration file.

apiVersion: 1
    
providers:
- name: dashboards
  type: file
  updateIntervalSeconds: 30
  options:
    path: /etc/dashboards
    foldersFromFileStructure: true
server and application will become new folders in Grafana menu.

**How to reproduce it** (as minimally and precisely as possible):
Place the following in values.yaml:
grafana:
  defaultDashboardsEnabled: false
  sidecar:
    dashboards:
      enabled: false
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: test
        type: file
        disableDeletion: true
        editable: false        
        options:
          path: /var/lib/grafana/dashboards/test
          foldersFromFileStructure: true

Launch prometheus-operator using Helm

**Anything else we need to know**:

**Comment by ansjcy** [comment] 2020-07-01 21:04
The tag name is really confusing. On the document both `foldersFromFileStructure` and `foldersFromFilesStructure` are used: https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards.
Not sure which is the correct one.
`foldersFromFileStructure` doesn't work in my test setup.

**Comment by eesperi** [comment] 2020-07-02 17:41
> The tag name is really confusing. On the document both `foldersFromFileStructure` and `foldersFromFilesStructure` are used: https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards.
> Not sure which is the correct one.
> Update: `foldersFromFileStructure` doesn't work in my test setup.

I noticed that error too. I tried both with no luck. Did you get foldersFromFilesStructure to work?

**Comment by geekq** [comment] 2020-08-13 14:48
`foldersFromFilesStructure` (with both 's' at the end of 'folders' and 'Files') does not work for me either, newest Grafana 7.1.3, using with prom-operator as well. Mounted dashboard definitions inside subfolders, but all dashboards are shown under `General`

Possible duplicate of https://github.com/grafana/grafana/issues/26223

**Comment by eesperi** [comment] 2020-08-13 22:55
> `foldersFromFilesStructure` (with both 's' at the end of 'folders' and 'Files') does not work for me either, newest Grafana 7.1.3, using with prom-operator as well. Mounted dashboard definitions inside subfolders, but all dashboards are shown under `General`
> 
> Possible duplicate of [grafana/grafana#26223](https://github.com/grafana/grafana/issues/26223)

The correct option is 'foldersFromFilesStructure'. Make sure that your .json files have empty UID fields.

**Comment by scottrigby** [comment] 2020-09-09 21:12
🚧 This chart is now deprecated.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). The chart has been renamed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to more clearly reflect that it installs the `kube-prometheus` project stack, within which Prometheus Operator is only one component.

If applicable, please re-open this issue there. Thanks!

**Closed as completed by scottrigby** 2020-09-09 21:12 UTC
