### ISSUE TITLE
[Stable/MariaDB] PVC being created even persistence.enabled = false

### ISSUE THREAD

**Issue by michelleN** [helm/charts#138] opened 2016-10-21 13:38 UTC
Steps to re-create:
`helm install stable/mariadb --set persistence.enabled=false`

You'll see that when you do a `helm get [RELEASE]` the value of persistence.enabled is set correctly to false but the PVC is still being created.

Version info:

```
$ helm version
Client: &version.Version{SemVer:"v2.0.0-beta.1", GitCommit:"58be8c9fce50f0657425443b83307ba91789b794", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.0.0-beta.1", GitCommit:"2eed3f0464ff88d1c8358388ce5472e835c35feb", GitTreeState:"clean"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1+33cf7b9", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"not a git tree", BuildDate:"2016-10-13T15:18:15Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"dirty", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by michelleN** [comment] 2016-10-21 13:51
Seeing same behavior on stable/mysql.

**Comment by prydonius** [comment] 2016-10-21 15:21
Hey @michelleN, I've actually noticed this before and the issue is helm's `--set` option doesn't parse booleans, it treats every value as a string. So, currently, the only way to disable persistence is with a custom YAML file.

**Comment by prydonius** [comment] 2016-10-27 23:43
This is fixed as of beta.2

**Closed as completed by prydonius** 2016-10-27 23:43 UTC

**Comment by zerogvt** [comment] 2018-11-30 19:13
I'm seeing this currently.
Versions info:
```
>$ helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

>$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.8+IKS", GitCommit:"0de1eb15c966d70e3aab059d273772a6cd7ec3ca", GitTreeState:"clean", BuildDate:"2018-11-01T06:07:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
